### ISSUE TITLE
Disabling skill rust

### ISSUE THREAD

**Issue by random-cdda-modder** [neonspectra/CDDA-Choice#2]
You can take the Good Memory trait, call it "Disable skill rust", make it 0 points and make the multiplier 0.

If that won't work because someone is dividing by the multiplier, make the multiplier 0.00000000000000000000000001

I have not tested this at all.

https://github.com/CleverRaven/Cataclysm-DDA/blob/13f8d81b4830226ad24345d0dcf1b00fc3fd5dad/data/json/mutations/mutations.json#L855

```json
{
    "type": "mutation",
    "id": "GOODMEMORY",
    "name": { "str": "Disable Skill Rust" },
    "points": 0,
    "description": "Your skills will not erode.",
    "types": [ "MEMORY" ],
    "skill_rust_multiplier": 0,
    "starting_trait": true,
    "valid": false,
    "cancels": [ "FORGETFUL" ]
}
```

**Comment by BananaBonanza** [comment]
I made the above edits to a copy of Experimental Build 2023-04-15-0610. Initial testing looks like this works without any 'divide by zero' errors (that I've seen so far, anyway).

Made a new character, did not select the new trait and began playing with 1 point in every skill. After waiting two days everything had started to degrade. Skills were now at level 0 with percentages in then 90s. Debug'd the character to have the trait, trained up athletics via the "practice" craft, and then waited several more days. No skill rust after that point.

**Comment by neonspectra** [comment]
Thanks for this! I think the path forward with this one is to try merging into CleverRaven as a debug option, since that would make it easier on everyone involved imo.

I created [a new PR in CleverRaven](https://github.com/CleverRaven/Cataclysm-DDA/pull/65141) as a debug option...
- If it gets merged, I'll include steps on how to activate it in-game in the guide.
- If it doesn't, I'll add a mod to add this mutation in and document how it works

---

BTW, @random-cdda-modder, I was going to add you as a co-author, but it seems you just created your GitHub account and do not have any commits that I can grab your committer signature from.

If you provide your [GitHub NoReply commit address](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address#setting-your-commit-email-address-on-github), I'd be happy to add a commit with you as a co-author.

**Comment by captainsawbones** [comment]
Hey!  I saw your commit got shot down, so I figured I'd take @random-cdda-modder 's idea and package it into its little own baby standalone mod to make life a little bit easier for you guys.  I made it clear that RCM' was the one who came up with the idea in the modinfo and the readme, and i'll link you to my repository.  I hope that's okay (contributing properly to things /collaborating on github is new to me and I don't really know the proper way to do things yet.)  [here's that repository](https://github.com/captainsawbones/CDDA-Skill-Antirust)

**Comment by random-cdda-modder** [comment]
I hereby relinquish all authorship and copyright for anything related to this issue, feel free to do what you want without even attribution or anything. Ideas are free, execution is golden

**Comment by neonspectra** [comment]
@captainsawbones Thanks! I really appreciate your contribution. I added some documentation to this repo pointing to your mod along with the explanation of how it works.

Welcome to collaborating on GitHub-- it's really daunting and unintuitive and I had a hard time with it too when I started. There's a reason they call git [the stupid content tracker](https://git-scm.com/docs/git) 😉 .

BTW I sent over a pull request to your repo with some suggestions. Please feel free to review at your convenience if they're things that you want to put in.

**Comment by neonspectra** [comment]
Thanks everyone for all the contributions on getting this one documented!
